M48
; DRILL file {KiCad 9.0.0} date 2025-04-05T15:37:13+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-05T15:37:13+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X109.0Y-79.0
X109.0Y-102.0
X154.0Y-79.0
X154.0Y-102.0
T2
X111.18Y-89.2
M30
